### ISSUE TITLE
How to make sure this by RSS3: "Censorship is also greatly suppressed with only some specific cases such as parental control."

### ISSUE THREAD

**Issue by Colstuwjx** [NaturalSelectionLabs/RSS3#13]
RSS3 is a great idea, and I've read the lite paper.

My question is if we allow content censorship as VII Threat Model C. Censorship said, content censorship might be possible on a per-platform or application basis, how could we ensure that **censorship would also be greatly suppressed with only some specific cases such as parental control.** ?

Thanks!

**Comment by joshuaTTL** [comment]
Good question. 
It's up to the application to implement something like "parent control" or any type of filtering or censorship. If users choose to use such feature in such application, then they can get a censored feed. However, the RSS3 network will have no censorship whatsoever, which means you can always change the app and see the feed without any interference. Since possible censorship can only happen within specific app(s), it will be greatly suppressed compared to any centralized system.
